name: run main.py

on:
  schedule:
    - cron: '0/3 * * * *'  # Every minute  

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # Specify the version of the checkout action compatible with Node.js version 16

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Install Python 3.10
      - name: activate virtual environment
        run: source venv/bin/activate

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python main.py
