name: Run web scraper

on: 
  schedule:
    - cron: '* * * * *' # Runs every other hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute py script
        run: python asynchronous.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update courses.md
        id: auto-commit-action

      - name: Send email
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_ADDR}}
          password: ${{secrets.MAIL_PASS}}
          subject: 'HOT DISCOUNTS'
          to: ismetsemedov@gmail.com
          from: Discounts
          html_body: file://mark.md
          convert_markdown: true